<?php

namespace ContainerXv2wm5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3qZhBnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3q_zhBn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3q_zhBn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'image' => ['privates', '.errored..service_locator.3q_zhBn.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.3q_zhBn": it references class "App\\Entity\\Images" but no such service exists.'],
            'request' => ['privates', '.errored.LVtpwWA', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::deleteImage()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Resquest". Did you forget to add a use statement?'],
        ], [
            'image' => 'App\\Entity\\Images',
            'request' => '?',
        ]);
    }
}
