<?php

namespace ContainerZLeqtUK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UD_QrhUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UD.qrhU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UD.qrhU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AcceuilController::HomePage' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AnnoncesControllerV2::Post' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.LfWppqE', 'get_ServiceLocator_LfWppqEService', true],
            'App\\Controller\\SecurityController::index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::EditProfilePage' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\UserController::deleteImage' => ['privates', '.service_locator.3q_zhBn', 'get_ServiceLocator_3qZhBnService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AcceuilController:HomePage' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AnnoncesControllerV2:Post' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.LfWppqE', 'get_ServiceLocator_LfWppqEService', true],
            'App\\Controller\\SecurityController:index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:EditProfilePage' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\UserController:deleteImage' => ['privates', '.service_locator.3q_zhBn', 'get_ServiceLocator_3qZhBnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AcceuilController::HomePage' => '?',
            'App\\Controller\\AnnoncesControllerV2::Post' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::index' => '?',
            'App\\Controller\\UserController::EditProfilePage' => '?',
            'App\\Controller\\UserController::deleteImage' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AcceuilController:HomePage' => '?',
            'App\\Controller\\AnnoncesControllerV2:Post' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:index' => '?',
            'App\\Controller\\UserController:EditProfilePage' => '?',
            'App\\Controller\\UserController:deleteImage' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
