<?php

namespace ContainerMZbkCWD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EJqgF0YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EJqgF0Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EJqgF0Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annonce' => ['privates', '.errored..service_locator.EJqgF0Y.App\\Entity\\Annonces', NULL, 'Cannot autowire service ".service_locator.EJqgF0Y": it references class "App\\Entity\\Annonces" but no such service exists.'],
        ], [
            'annonce' => 'App\\Entity\\Annonces',
        ]);
    }
}
