<?php

namespace ContainerMZbkCWD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nu54vqiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nu54vqi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nu54vqi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AcceuilController::HomePage' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AcceuilController::Post' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AnnoncesController::delete' => ['privates', '.service_locator.EJqgF0Y', 'get_ServiceLocator_EJqgF0YService', true],
            'App\\Controller\\AnnoncesController::edit' => ['privates', '.service_locator.EJqgF0Y', 'get_ServiceLocator_EJqgF0YService', true],
            'App\\Controller\\AnnoncesController::index' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AnnoncesController::show' => ['privates', '.service_locator.EJqgF0Y', 'get_ServiceLocator_EJqgF0YService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.LfWppqE', 'get_ServiceLocator_LfWppqEService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::EditProfilePage' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AcceuilController:HomePage' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AcceuilController:Post' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AnnoncesController:delete' => ['privates', '.service_locator.EJqgF0Y', 'get_ServiceLocator_EJqgF0YService', true],
            'App\\Controller\\AnnoncesController:edit' => ['privates', '.service_locator.EJqgF0Y', 'get_ServiceLocator_EJqgF0YService', true],
            'App\\Controller\\AnnoncesController:index' => ['privates', '.service_locator.FrIHHjC', 'get_ServiceLocator_FrIHHjCService', true],
            'App\\Controller\\AnnoncesController:show' => ['privates', '.service_locator.EJqgF0Y', 'get_ServiceLocator_EJqgF0YService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.LfWppqE', 'get_ServiceLocator_LfWppqEService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:EditProfilePage' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AcceuilController::HomePage' => '?',
            'App\\Controller\\AcceuilController::Post' => '?',
            'App\\Controller\\AnnoncesController::delete' => '?',
            'App\\Controller\\AnnoncesController::edit' => '?',
            'App\\Controller\\AnnoncesController::index' => '?',
            'App\\Controller\\AnnoncesController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::EditProfilePage' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AcceuilController:HomePage' => '?',
            'App\\Controller\\AcceuilController:Post' => '?',
            'App\\Controller\\AnnoncesController:delete' => '?',
            'App\\Controller\\AnnoncesController:edit' => '?',
            'App\\Controller\\AnnoncesController:index' => '?',
            'App\\Controller\\AnnoncesController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:EditProfilePage' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
