<?php

namespace Container76Rdk6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_LVtpwWAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.LVtpwWA' shared service.
     *
     * @return \App\Controller\Resquest
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::deleteImage()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Resquest". Did you forget to add a use statement?');
    }
}
