<?php

namespace Container1LHM4xd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V_GjHUjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V.gjHUj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V.gjHUj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annoncesRepository' => ['privates', '.errored.5TfNmXk', NULL, 'Cannot determine controller argument for "App\\Controller\\ApiController::list()": the $annoncesRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\AnnoncesRepository". Did you forget to add a use statement?'],
        ], [
            'annoncesRepository' => '?',
        ]);
    }
}
