<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZRMmST3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZRMmST3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZRMmST3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZRMmST3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZRMmST3\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZRMmST3',
    'container.build_id' => 'd44494e7',
    'container.build_time' => 1609091782,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZRMmST3');
