<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZbkCWD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZbkCWD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZbkCWD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZbkCWD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMZbkCWD\App_KernelDevDebugContainer([
    'container.build_hash' => 'MZbkCWD',
    'container.build_id' => '8632de1a',
    'container.build_time' => 1609190147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZbkCWD');
