<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZLeqtUK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZLeqtUK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZLeqtUK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZLeqtUK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZLeqtUK\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZLeqtUK',
    'container.build_id' => '82b1198b',
    'container.build_time' => 1609256718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZLeqtUK');
