<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_Acceuil' => [[], ['_controller' => 'App\\Controller\\AcceuilController::HomePage'], [], [['text', '/Acceuil']], [], []],
    'app_post' => [[], ['_controller' => 'App\\Controller\\AcceuilController::Post'], [], [['text', '/Post']], [], []],
    'app_post_new' => [[], ['_controller' => 'App\\Controller\\AcceuilController::new'], [], [['text', '/Post/new']], [], []],
    'annonces_index' => [[], ['_controller' => 'App\\Controller\\AnnoncesController::index'], [], [['text', '/annonces/']], [], []],
    'annonces_new' => [[], ['_controller' => 'App\\Controller\\AnnoncesController::new'], [], [['text', '/annonces/new']], [], []],
    'annonces_show' => [['id'], ['_controller' => 'App\\Controller\\AnnoncesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/annonces']], [], []],
    'annonces_edit' => [['id'], ['_controller' => 'App\\Controller\\AnnoncesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/annonces']], [], []],
    'annonces_delete' => [['id'], ['_controller' => 'App\\Controller\\AnnoncesController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/annonces']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'app_Profile' => [[], ['_controller' => 'App\\Controller\\UserController::ProfilePage'], [], [['text', '/User']], [], []],
    'app_EditProfile' => [[], ['_controller' => 'App\\Controller\\UserController::EditProfilePage'], [], [['text', '/User/Edit']], [], []],
];
